// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xetjkdixtxzzjguonrmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhldGprZGl4dHh6empndW9ucm16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NzA5OTQsImV4cCI6MjA3NDE0Njk5NH0.tkHmELH7T4BtFP2U5xI-x4-2qywpWWD9oFB1kZshawg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});